<?php
define('CL_USER', $_SERVER['DOCUMENT_ROOT'].DIRECTORY_SEPARATOR.'class'.DIRECTORY_SEPARATOR.'user.php');
define('CL_ANNOUNCEMENT', $_SERVER['DOCUMENT_ROOT'].DIRECTORY_SEPARATOR.'class'.DIRECTORY_SEPARATOR.'announcement.php');
define('CONNECT', $_SERVER['DOCUMENT_ROOT'].DIRECTORY_SEPARATOR.'ops'.DIRECTORY_SEPARATOR.'connect.php');
?>
